/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.interagese.interfiscal.view;

import br.com.interagese.interfiscal.business.FireTabproBusinessBean;
import br.com.interagese.interfiscal.business.FireTabprofilBusinessBean;
import br.com.interagese.interfiscal.business.FireTabproimpBusinessBean;
import br.com.interagese.interfiscal.business.TabfilBusiness;
import br.com.interagese.interfiscal.business.TabfilBusinessBean;
import br.com.interagese.interfiscal.entity.ImportacaoImp;
import br.com.interagese.interfiscal.entity.Tabfil;
import br.com.interagese.interfiscal.entity.Tabpro;
import br.com.interagese.interfiscal.entity.Tabprofil;
import br.com.interagese.interfiscal.entity.Tabproimp;
import br.com.interagese.interfiscal.message.OptionPane;
import br.com.interagese.interfiscal.table.ItensTableModel;
import br.com.interagese.interfiscal.utils.Actions;
import br.com.interagese.interfiscal.utils.Utils;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.TypedQuery;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.plaf.metal.MetalButtonUI;
import org.apache.poi.hssf.usermodel.HSSFCellStyle;
import org.apache.poi.hssf.usermodel.HSSFFont;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.Row;

/**
 *
 * @author bruno
 */
public class InterImposto extends JInternalFrame {
    
    private JFrame jFramePrincipal;
    private Actions a = new Actions();
    private ItensTableModel tableModel = null;
    private FireTabproBusinessBean fireTabproBusiness = new FireTabproBusinessBean();
    private FireTabproimpBusinessBean fireTabproimpBusinessBean = new FireTabproimpBusinessBean();
    private FireTabprofilBusinessBean fireTabprofilBusinessBean = new FireTabprofilBusinessBean();
    private TabfilBusiness tabfilBusiness = new TabfilBusinessBean();
    private Integer codfil = null;
    private Integer tipo = null;
    private boolean exportAll = false;

    /**
     * Creates new form JfrmPrincipal
     */
    public InterImposto(JFrame pai) {
        jFramePrincipal = pai;
        initComponents();
        definirFormulario();
    }
    
    public void definirFormulario() {
        this.setTitle("Importação de Imposto");
        a.iconApplicationInternalFrame(this);
        
        tipo = jCbxTipo.getSelectedIndex();
        jCbxFilial.setModel(new DefaultComboBoxModel(tabfilBusiness.getAll().toArray(new Tabfil[]{})));
        codfil = jCbxFilial.getItemAt(0).getCodfil();
        carregarImpostos();
        
    }
    
    public void carregarImpostos() {
        jTxtProd.setText("");
        tableModel = new ItensTableModel(fireTabproBusiness.getImportacaoImpostosLimit(codfil, tipo));
        jTable.setModel(tableModel);
        JlblTotal.setText("" + ((Number) fireTabproBusiness.countImportacao(codfil, tipo)).intValue());
        
        jTable.setAutoResizeMode(jTable.AUTO_RESIZE_OFF);
        a.setColumnMinWidth(jTable, 0, 300);
        a.setColumn(jTable, 1, 150);
        a.setColumn(jTable, 2, 150);
        a.setColumn(jTable, 3, 150);
        a.setColumn(jTable, 4, 120);
        a.setColumn(jTable, 5, 120);
        a.setColumn(jTable, 6, 120);
        a.setColumn(jTable, 7, 120);
        a.setColumn(jTable, 8, 120);
        a.setColumn(jTable, 9, 120);
        a.setColumn(jTable, 10, 120);
        a.setColumn(jTable, 11, 120);
        a.setColumn(jTable, 12, 150);
        a.setColumn(jTable, 13, 150);
        a.setColumn(jTable, 14, 150);
        a.setColumn(jTable, 15, 150);
        jButton1.setUI(new MetalButtonUI());
        jButton2.setUI(new MetalButtonUI());
        jButton3.setUI(new MetalButtonUI());
        exportAll = true;
        jTxtProd.requestFocus();
    }
    
    public JDlgCarregando carregarJdialog(String txt) {
        JDlgCarregando carregando = new JDlgCarregando(jFramePrincipal, false, txt);
        return carregando;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){
            protected  void paintComponent(Graphics g){
                super.paintComponent(g);
                ImageIcon icon = new ImageIcon(getClass().getResource("/imagens/fundo.png"));
                Image image = icon.getImage();
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }};
            jScrollPane1 = new javax.swing.JScrollPane();
            jTable = new javax.swing.JTable();
            jButton1 = new javax.swing.JButton();
            jButton2 = new javax.swing.JButton();
            jPanel2 = new javax.swing.JPanel();
            jLabel1 = new javax.swing.JLabel();
            JlblTotal = new javax.swing.JLabel();
            jCbxFilial = new javax.swing.JComboBox<>();
            jButton3 = new javax.swing.JButton();
            jLabel2 = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            jTxtProd = new javax.swing.JTextField();
            jLabel4 = new javax.swing.JLabel();
            jCbxTipo = new javax.swing.JComboBox<>();

            setClosable(true);
            setIconifiable(true);
            setMaximizable(true);
            setResizable(true);
            getContentPane().setLayout(new java.awt.CardLayout());

            jTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
                }
            ));
            jTable.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jTableMouseClicked(evt);
                }
            });
            jTable.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    jTableKeyPressed(evt);
                }
            });
            jScrollPane1.setViewportView(jTable);

            jButton1.setBackground(new java.awt.Color(0, 51, 102));
            jButton1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
            jButton1.setForeground(new java.awt.Color(255, 255, 255));
            jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/import2424.png"))); // NOI18N
            jButton1.setMnemonic('i');
            jButton1.setText(" [ ALT + I ] - Importar Arquivo(Excel)");
            jButton1.setToolTipText(" [ ALT + I ] - Importar Arquivo(Excel)");
            jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
            jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jButton1.setFocusable(false);
            jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            jButton1.setMargin(new java.awt.Insets(2, 0, 2, 14));
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            jButton2.setBackground(new java.awt.Color(0, 51, 102));
            jButton2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
            jButton2.setForeground(new java.awt.Color(255, 255, 255));
            jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/export2424.png"))); // NOI18N
            jButton2.setMnemonic('e');
            jButton2.setText(" [ ALT + E ] - Exportar Arquivo(Excel)");
            jButton2.setToolTipText(" [ ALT + E ] - Exportar Arquivo(Excel)");
            jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
            jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jButton2.setFocusable(false);
            jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            jButton2.setMargin(new java.awt.Insets(2, 0, 2, 14));
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });

            jPanel2.setBackground(new java.awt.Color(58, 53, 53));
            jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true));

            jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
            jLabel1.setForeground(new java.awt.Color(255, 255, 255));
            jLabel1.setText("Total Itens :");

            JlblTotal.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
            JlblTotal.setForeground(new java.awt.Color(255, 255, 255));
            JlblTotal.setText("0");

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(30, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(JlblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JlblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(6, 6, 6))
            );

            jCbxFilial.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
            jCbxFilial.addItemListener(new java.awt.event.ItemListener() {
                public void itemStateChanged(java.awt.event.ItemEvent evt) {
                    jCbxFilialItemStateChanged(evt);
                }
            });
            jCbxFilial.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jCbxFilialActionPerformed(evt);
                }
            });

            jButton3.setBackground(new java.awt.Color(0, 51, 102));
            jButton3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
            jButton3.setForeground(new java.awt.Color(255, 255, 255));
            jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search.png"))); // NOI18N
            jButton3.setText("Pesquisar");
            jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
            jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jButton3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton3ActionPerformed(evt);
                }
            });

            jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
            jLabel2.setForeground(new java.awt.Color(255, 255, 255));
            jLabel2.setText("<html><u>Filal:</u></html>");

            jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
            jLabel3.setForeground(new java.awt.Color(255, 255, 255));
            jLabel3.setText("<html><u>Produto:</u></html>");

            jTxtProd.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
            jTxtProd.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    jTxtProdKeyPressed(evt);
                }
            });

            jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
            jLabel4.setForeground(new java.awt.Color(255, 255, 255));
            jLabel4.setText("<html><u>Tipo:</u></html>");

            jCbxTipo.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
            jCbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Normal", "Mix-Fiscal" }));
            jCbxTipo.addItemListener(new java.awt.event.ItemListener() {
                public void itemStateChanged(java.awt.event.ItemEvent evt) {
                    jCbxTipoItemStateChanged(evt);
                }
            });

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton2))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTxtProd, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(jCbxFilial, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 32, Short.MAX_VALUE)))
                    .addContainerGap())
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTxtProd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCbxTipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCbxFilial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)
                        .addComponent(jButton2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );

            getContentPane().add(jPanel1, "card2");

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        if (evt.getClickCount() == 2) {
//            openDialogItens();
        }
    }//GEN-LAST:event_jTableMouseClicked

    private void jTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
//            openDialogItens();
        }
    }//GEN-LAST:event_jTableKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            new Thread(new Runnable() {
                @Override
                public void run() {
                    
                    JDlgCarregando carregando = carregarJdialog("Exportando...");
                    if (!tableModel.getResultList().isEmpty()) {
                        JFileChooser chooser = new JFileChooser();
                        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
                        int i = chooser.showSaveDialog(jFramePrincipal);
                        if (i == JFileChooser.APPROVE_OPTION) {
                            carregando.setVisible(true);
                            carregando.loadBarra("Exportando Arquivo Excel...", 0, 0, true);
                            i = 0;
                            String filename = chooser.getSelectedFile().getAbsolutePath() + ".xls";
                            HSSFWorkbook workbook = new HSSFWorkbook();
                            HSSFSheet sheet = workbook.createSheet("FirstSheet");
                            
                            HSSFCellStyle txtStyle1 = (HSSFCellStyle) workbook.createCellStyle();
                            HSSFCellStyle txtStyle2 = (HSSFCellStyle) workbook.createCellStyle();
                            HSSFCellStyle txtStyle3 = (HSSFCellStyle) workbook.createCellStyle();
                            
                            HSSFFont txtFont1 = (HSSFFont) workbook.createFont();
                            HSSFFont txtFont2 = (HSSFFont) workbook.createFont();
                            HSSFFont txtFont3 = (HSSFFont) workbook.createFont();
                            
                            txtFont1.setFontName("Arial");
                            txtFont1.setFontHeightInPoints((short) 18);
                            txtFont1.setBold(true);
                            txtFont1.setColor((short) 003366);
                            txtStyle1.setFont(txtFont1);
                            
                            txtFont2.setFontHeightInPoints((short) 14);
                            txtFont2.setFontName("Arial");
                            txtFont2.setColor((short) 003366);
                            txtStyle2.setFont(txtFont2);
                            
                            txtFont3.setFontHeightInPoints((short) 11);
                            txtFont3.setFontName("Arial");
                            txtFont3.setBold(true);
                            txtFont3.setColor((short) 003366);
                            txtStyle3.setFont(txtFont3);

                            //******************* titulo ************************
                            HSSFRow rowTitulo = sheet.createRow((short) i++);
                            rowTitulo.createCell(4).setCellValue("Importação de Impostos");
                            rowTitulo.getCell(4).setCellStyle(txtStyle1);
                            
                            HSSFRow rowfilial = sheet.createRow((short) i++);
                            rowfilial.createCell(0).setCellValue("Filial: ");
                            rowfilial.createCell(1).setCellValue(((Tabfil) jCbxFilial.getModel().getSelectedItem()).toString());
//                            rowfilial.createCell(5).setCellValue("          Consumidor Final        ");
                            rowfilial.getCell(0).setCellStyle(txtStyle2);
                            rowfilial.getCell(1).setCellStyle(txtStyle2);
//                            rowfilial.getCell(5).setCellStyle(txtStyle2);

                            HSSFRow rowHeader2 = sheet.createRow((short) i++);
                            rowHeader2.createCell(0).setCellValue("Produto");
                            rowHeader2.createCell(1).setCellValue("Cód Produto");
                            rowHeader2.createCell(2).setCellValue("Cód Barras");
                            rowHeader2.createCell(3).setCellValue("Gênero");
                            rowHeader2.createCell(4).setCellValue("NCM");
                            rowHeader2.createCell(5).setCellValue("CFOP");
                            rowHeader2.createCell(6).setCellValue("CEST");
                            rowHeader2.createCell(7).setCellValue("CST");
                            rowHeader2.createCell(8).setCellValue("Icms Saída");
                            rowHeader2.createCell(9).setCellValue("Pis Entrada");
                            rowHeader2.createCell(10).setCellValue("Pis Saída");
                            rowHeader2.createCell(11).setCellValue("Cofins Entrada");
                            rowHeader2.createCell(12).setCellValue("Cofins Saída");
                            rowHeader2.createCell(13).setCellValue("Nat Produto");
                            rowHeader2.createCell(14).setCellValue("Alíquota Pis");
                            rowHeader2.createCell(15).setCellValue("Alíquota Cofins");
                            rowHeader2.getCell(0).setCellStyle(txtStyle3);
                            rowHeader2.getCell(1).setCellStyle(txtStyle3);
                            rowHeader2.getCell(2).setCellStyle(txtStyle3);
                            rowHeader2.getCell(3).setCellStyle(txtStyle3);
                            rowHeader2.getCell(4).setCellStyle(txtStyle3);
                            rowHeader2.getCell(5).setCellStyle(txtStyle3);
                            rowHeader2.getCell(6).setCellStyle(txtStyle3);
                            rowHeader2.getCell(7).setCellStyle(txtStyle3);
                            rowHeader2.getCell(8).setCellStyle(txtStyle3);
                            rowHeader2.getCell(9).setCellStyle(txtStyle3);
                            rowHeader2.getCell(10).setCellStyle(txtStyle3);
                            rowHeader2.getCell(11).setCellStyle(txtStyle3);
                            rowHeader2.getCell(12).setCellStyle(txtStyle3);
                            rowHeader2.getCell(13).setCellStyle(txtStyle3);
                            rowHeader2.getCell(14).setCellStyle(txtStyle3);
                            rowHeader2.getCell(15).setCellStyle(txtStyle3);

                            //***************************************************
                            DecimalFormat Formata = new DecimalFormat("#,##0.00000");
                            int cont = 1;
                            List<ImportacaoImp> resultImp = null;
                            if (exportAll) {
                                resultImp = fireTabproBusiness.getImportacaoImpostosAll(codfil, tipo);
                            } else {
                                resultImp = tableModel.getItens();
                            }
                            for (ImportacaoImp item : resultImp) {
                                carregando.loadBarra("Exportando Tributação ", cont, resultImp.size(), false);
                                HSSFRow rowHeader3 = sheet.createRow(i++);
                                rowHeader3.createCell(0).setCellValue(item.getNomeproduto());
                                rowHeader3.createCell(1).setCellValue(item.getCodigoproduto());
                                rowHeader3.createCell(2).setCellValue(item.getCodigobarra());
                                rowHeader3.createCell(3).setCellValue(item.getGenero());
                                rowHeader3.createCell(4).setCellValue(item.getNcm());
                                rowHeader3.createCell(5).setCellValue(item.getCfop());
                                rowHeader3.createCell(6).setCellValue(item.getCest());
                                rowHeader3.createCell(7).setCellValue(item.getCst());
                                rowHeader3.createCell(8).setCellValue(item.getIcmsSaida());
                                rowHeader3.createCell(9).setCellValue(item.getPisentrada());
                                rowHeader3.createCell(10).setCellValue(item.getPissaida());
                                rowHeader3.createCell(11).setCellValue(item.getCofinsentrada());
                                rowHeader3.createCell(12).setCellValue(item.getCofinssaida());
                                rowHeader3.createCell(13).setCellValue(item.getNaturezaproduto());
                                rowHeader3.createCell(14).setCellValue(Formata.format(item.getAliquotaPis()));
                                rowHeader3.createCell(15).setCellValue(Formata.format(item.getAliquotaCofins()));
                                
                                cont++;
                            }
                            try {
                                FileOutputStream fileOut = new FileOutputStream(filename);
                                workbook.write(fileOut);
                                fileOut.close();
                                workbook.close();
                                carregando.setVisible(false);
                                OptionPane.showMessageDialog("Mensagem", "Arquivo Exportado com Sucesso", null, () -> {
                                    
                                    Thread.sleep(1000);
                                    
                                    return null; //To change body of generated lambdas, choose Tools | Templates.
                                });
                            } catch (Exception ex) {
                                JDlgMensagem mensagem = new JDlgMensagem(jFramePrincipal, true, ex);
                                System.out.println(ex.getMessage());
                                mensagem.setVisible(true);
                            }
                            
                        } else {
                            JOptionPane.showMessageDialog(jFramePrincipal, "Operação cancelada pelo usuário!!", null, JOptionPane.ERROR_MESSAGE);
                        }
                        
                    }
                }
            }).start();
        } catch (Exception ex) {
            JDlgMensagem mensagem = new JDlgMensagem(jFramePrincipal, true, ex);
            System.out.println(ex.getMessage());
            mensagem.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int resp = JOptionPane.showConfirmDialog(this, "Deseja realmente sair do sistema?", null, JOptionPane.YES_NO_OPTION);
        if (resp == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        boolean resp = jDlgBoasVindas.jDlgBoasVindasIniciar(jFramePrincipal);
    }//GEN-LAST:event_formWindowOpened
    

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        Thread action = null;
        try {
            List<ImportacaoImp> result = new ArrayList<>();
            JFileChooser chooser = new JFileChooser();
            chooser.setMultiSelectionEnabled(true);
            chooser.setFileFilter(new FileNameExtensionFilter("Arquivos do Excel", "xlsx", "xlsm", "xlsb", "xltx", "xltm", "xls", "xlt", "xml", "xlam", "xla", "xlw", "xlr", "csv"));
            int resp = chooser.showOpenDialog(this);
            if (resp == JFileChooser.APPROVE_OPTION) {
                for (File f : chooser.getSelectedFiles()) {
                    FileInputStream fips = new FileInputStream(f);
                    HSSFWorkbook workbook = new HSSFWorkbook(fips);
                    HSSFSheet linhas = workbook.getSheetAt(0);
                    
                    for (int i = 0; i < linhas.getPhysicalNumberOfRows(); i++) {
                        Row linha = linhas.getRow(i);
                        if (i == 1) {
                            codfil = Integer.parseInt(linha.getCell(1).getRichStringCellValue().toString().split("-")[0].trim());
                        }
                        if (i > 2) {
                            ImportacaoImp imp = new ImportacaoImp();
//                            imp.setNomeproduto(linha.getCell(0).getCellTypeEnum().name().equals("STRING") ? linha.getCell(0).getRichStringCellValue().toString() : ((Double) linha.getCell(0).getNumericCellValue()).toString().replace(".0", ""));
//                            imp.setNomeproduto(((Double) linha.getCell(0).getNumericCellValue()).toString());
                            imp.setNomeproduto(linha.getCell(0).getCellTypeEnum().name().equals("STRING") ? linha.getCell(0).getRichStringCellValue().toString() : ((Double) linha.getCell(0).getNumericCellValue()).toString().replace(".0", ""));
                            imp.setCodigoproduto(linha.getCell(1).getCellTypeEnum().name().equals("STRING") ? linha.getCell(1).getRichStringCellValue().toString() : ((Double) linha.getCell(1).getNumericCellValue()).toString().replace(".0", ""));
                            imp.setCodigobarra(Utils.retirarCaracteresEspeciais(linha.getCell(2).getCellTypeEnum().name().equals("STRING") ? linha.getCell(2).getRichStringCellValue().toString().replace("E12", "").replace("E7", "").replace(".", "") : ((Double) linha.getCell(2).getNumericCellValue()).toString().replace(".0", "")));
                            imp.setGenero(linha.getCell(3).getCellTypeEnum().name().equals("STRING") ? linha.getCell(3).getRichStringCellValue().toString() : ((Double) linha.getCell(3).getNumericCellValue()).toString().replace(".0", ""));
                            imp.setNcm(Utils.retirarCaracteresEspeciais(linha.getCell(4).getCellTypeEnum().name().equals("STRING") ? linha.getCell(4).getRichStringCellValue().toString() == null ? "0.0" : linha.getCell(4).getRichStringCellValue().toString().replace("E12", "").replace("E7", "").replace(".", "") : ((Double) linha.getCell(4).getNumericCellValue()).toString().replace(".0", "")));
                            imp.setCfop(linha.getCell(5).getCellTypeEnum().name().equals("STRING") ? linha.getCell(5).getRichStringCellValue().toString() == null ? "0.0" : linha.getCell(5).getRichStringCellValue().toString() : ((Double) linha.getCell(5).getNumericCellValue()).toString().replace(".0", ""));
                            imp.setCest(Utils.retirarCaracteresEspeciais(linha.getCell(6).getCellTypeEnum().name().equals("STRING") ? linha.getCell(6).getRichStringCellValue().toString() == null ? "0.0" : linha.getCell(6).getRichStringCellValue().toString() : ((Double) linha.getCell(6).getNumericCellValue()).toString().replace(".0", "")));
                            imp.setCst(linha.getCell(7).getCellTypeEnum().name().equals("STRING") ? linha.getCell(7).getRichStringCellValue().toString() == null ? "0.0" : linha.getCell(7).getRichStringCellValue().toString() : ((Double) linha.getCell(7).getNumericCellValue()).toString().replace(".0", ""));
                            imp.setIcmsSaida(linha.getCell(8).getCellTypeEnum().name().equals("STRING") ? new DecimalFormat("#,##0").parse(linha.getCell(8).getRichStringCellValue().toString() == null ? "0.0" : linha.getCell(8).getRichStringCellValue().toString().trim()).doubleValue() : linha.getCell(8).getNumericCellValue());
                            imp.setPisentrada(linha.getCell(9).getCellTypeEnum().name().equals("STRING") ? linha.getCell(9).getRichStringCellValue().toString() == null ? "0.0" : linha.getCell(9).getRichStringCellValue().toString().trim() : ((Double) linha.getCell(9).getNumericCellValue()).toString().replace(".0", ""));
                            imp.setPissaida(linha.getCell(10).getCellTypeEnum().name().equals("STRING") ? linha.getCell(10).getRichStringCellValue().toString() == null ? "0.0" : linha.getCell(10).getRichStringCellValue().toString().trim() : ((Double) linha.getCell(10).getNumericCellValue()).toString().replace(".0", ""));
                            imp.setCofinsentrada(linha.getCell(11).getCellTypeEnum().name().equals("STRING") ? linha.getCell(11).getRichStringCellValue().toString() == null ? "0.0" : linha.getCell(11).getRichStringCellValue().toString().trim() : ((Double) linha.getCell(11).getNumericCellValue()).toString().replace(".0", ""));
                            imp.setCofinssaida(linha.getCell(12).getCellTypeEnum().name().equals("STRING") ? linha.getCell(12).getRichStringCellValue().toString() == null ? "0.0" : linha.getCell(12).getRichStringCellValue().toString() : ((Double) linha.getCell(12).getNumericCellValue()).toString().replace(".0", ""));
                            imp.setNaturezaproduto(linha.getCell(13).getCellTypeEnum().name().equals("STRING") ? linha.getCell(13).getRichStringCellValue().toString() == null ? "0.0" : linha.getCell(13).getRichStringCellValue().toString().trim() : ((Double) linha.getCell(13).getNumericCellValue()).toString().replace(".0", ""));
                            imp.setAliquotaPis(linha.getCell(14).getCellTypeEnum().name().equals("STRING") ? new DecimalFormat("#,##0.00000").parse(linha.getCell(14).getRichStringCellValue().toString() == null ? "0.0" : linha.getCell(14).getRichStringCellValue().toString().trim()).doubleValue() : linha.getCell(14).getNumericCellValue());
                            imp.setAliquotaCofins(linha.getCell(15).getCellTypeEnum().name().equals("STRING") ? new DecimalFormat("#,##0.00000").parse(linha.getCell(15).getRichStringCellValue().toString() == null ? "0.0" : linha.getCell(15).getRichStringCellValue().toString().trim()).doubleValue() : linha.getCell(15).getNumericCellValue());
                            result.add(imp);
                        }
                    }

//                    Runnable runnable = new JDlgCarregandoApp.ShowAndWait(new Runnable() {
//                        @Override
//                        public void run() {
//                            try {
//                                
//                            } catch (Exception ex) {
//                                ex.getLocalizedMessage();
//                                JOptionPane.showMessageDialog(null, ex.getMessage());
//                            }
//                        }
//                    },this);
//                    runnable.run();
                    action = new Thread(new Runnable() {
                        @Override
                        public void run() {
                            
                            try {
                                JDlgCarregando carregando = carregarJdialog("Atualizando...");
                                carregando.setVisible(true);
                                String texto = "Iniciando Ajustes de Tributação fiscal ...";
                                carregando.loadBarra(texto, 0, 0, true);
                                
                                int i = 1;
                                String notTributation = "";
                                
                                for (ImportacaoImp imp : result) {
                                    carregando.loadBarra("Importando Tributação ", i, result.size(), false);
                                    boolean isExist = false;
                                    
                                    if (imp.getCodigobarra() != null && !imp.getCodigobarra().equals("")) {
                                        String query = "SELECT * FROM Tabpro tp WHERE tp.codbarun = '" + imp.getCodigobarra().trim() + "'";
                                        
                                        TypedQuery<Tabpro> listTp = (TypedQuery<Tabpro>) fireTabproBusiness.getDao().getEntityManager().createNativeQuery(query, Tabpro.class);
                                        if (!listTp.getResultList().isEmpty()) {
                                            Tabpro tp = listTp.getResultList().get(0);
                                            tp.setCodgen(imp.getGenero().trim());
                                            tp.setClasfiscal(imp.getNcm());
                                            tp.setCest(imp.getCest());
                                            tp.setNatpro(imp.getNaturezaproduto().trim());
                                            fireTabproBusiness.update(tp);
                                            String codPro = tp.getCodpro();
                                            
                                            TypedQuery<Tabprofil> listTpf = (TypedQuery<Tabprofil>) fireTabprofilBusinessBean.getDao().getEntityManager().createNativeQuery("select * from tabprofil tpf where tpf.codpro = :codpro and tpf.codfil = :codfil", Tabprofil.class).setParameter("codpro", codPro).setParameter("codfil", codfil);
                                            if (!listTpf.getResultList().isEmpty()) {
                                                Tabprofil tpf = listTpf.getResultList().get(0);
                                                tpf.setCstpise(imp.getPisentrada());
                                                tpf.setCstcofinse(imp.getCofinsentrada());
                                                fireTabprofilBusinessBean.update(tpf);
                                            } else if (imp.getPisentrada() != null || imp.getCofinsentrada() != null) {
                                                Tabprofil fil = new Tabprofil(codPro, codfil);
                                                fil.setCstpise(imp.getPisentrada());
                                                fil.setCstcofinse(imp.getCofinsentrada());
                                                fireTabprofilBusinessBean.insert(fil);
                                            }
                                            TypedQuery<Tabproimp> listTpi = (TypedQuery<Tabproimp>) fireTabproimpBusinessBean.getDao().getEntityManager().createNativeQuery("select * from tabproimp tpi where tpi.codpro = :codpro and tpi.codfil = :codfil and tpi.tpimpos='D'", Tabproimp.class).setParameter("codpro", codPro).setParameter("codfil", codfil);
                                            String crt = tabfilBusiness.findById(codfil).getCrt().toString();
                                            if (!listTpi.getResultList().isEmpty()) {
                                                Tabproimp tpi = listTpi.getResultList().get(0);
                                                tpi.setCfop(imp.getCfop());
                                                tpi.setIcmscst(crt.equals("1") ? imp.getCst() : imp.getCst().trim().length() == 3 ? imp.getCst().trim().substring(1) : imp.getCst().trim());
                                                tpi.setIcmspicms(imp.getIcmsSaida());
                                                tpi.setPiscst(imp.getPissaida());
                                                tpi.setCofinscst(imp.getCofinssaida());
                                                tpi.setPisppis(imp.getAliquotaPis());
                                                tpi.setCofinspcofins(imp.getAliquotaCofins());
                                                
                                                fireTabproimpBusinessBean.update(tpi);
                                            } else if ((imp.getCfop() != null && !imp.getCfop().equals("")) || imp.getPissaida() != null || imp.getCofinssaida() != null) {
                                                Tabproimp tpImp = new Tabproimp(codPro, codfil, "D");
                                                tpImp.setCfop(imp.getCfop());
                                                tpImp.setIcmscst(crt.equals("1") ? imp.getCst() : imp.getCst().trim().length() == 3 ? imp.getCst().trim().substring(1) : imp.getCst().trim());
                                                if (tpImp.getIcmscst().equals("00")) {
                                                    tpImp.setIcmsmodbc("3");
                                                }
                                                tpImp.setIcmspicms(imp.getIcmsSaida());
                                                tpImp.setPiscst(imp.getPissaida());
                                                tpImp.setCofinscst(imp.getCofinssaida());
                                                tpImp.setPisppis(imp.getAliquotaPis());
                                                tpImp.setCofinspcofins(imp.getAliquotaCofins());
                                                fireTabproimpBusinessBean.insert(tpImp);
                                            }
                                            isExist = true;
                                        }
                                    }
                                    
                                    if (!isExist) {
                                        notTributation += ("CodBarra = " + imp.getCodigobarra() + " Produto = " + imp.getNomeproduto() + "\n");
                                    }
                                    texto = (!isExist ? "!! Não Encontrado na Base de Dados !! " : "Posição = " + i) + "| codBarra = " + imp.getCodigobarra();
                                    carregando.setTexto(texto);
                                    i++;
                                }

//                                fireTabproBusiness.updateImpostoImp(result, codfil);
                                gerarArquivoNotTributation(notTributation);
                                carregarImpostos();
                                carregando.setVisible(true);
                                OptionPane.showMessageDialog("Mensagem", "Arquivo Importado com sucesso !!", null, () -> {
                                    
                                    Thread.sleep(1000);
                                    
                                    return null; //To change body of generated lambdas, choose Tools | Templates.
                                });
                            } catch (Exception ex) {
                                ex.printStackTrace();
                                JDlgMensagem mensagem = new JDlgMensagem(null, true, ex);
                                mensagem.setVisible(true);
//                                jProgressBar.setVisible(false);
                            }
                        }
                    });
                    action.start();
                    
                }
                
            } else {
                JOptionPane.showMessageDialog(this, "Operação cancelada pelo usuário!!", null, JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (Exception ex) {
            ex.printStackTrace();
            JDlgMensagem mensagem = new JDlgMensagem(jFramePrincipal, true, ex);
            mensagem.setVisible(true);
            action.stop();
//            jProgressBar.setVisible(false);
//            JOptionPane.showMessageDialog(this, ex.getMessage(), null, JOptionPane.ERROR_MESSAGE);
        }
//        JOptionPane.showMessageDialog(this, "!! Em desenvolvimento !! ");
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void gerarArquivoNotTributation(String texto) throws Exception {
        FileWriter arq = new FileWriter("C:\\InterageSe\\inter-fiscal\\Log-Importacao\\Log (" + (new SimpleDateFormat("dd-MM-yyyy HH:mm:ss").format(new Date())) + "");
        PrintWriter gravarArq = new PrintWriter(arq);
        gravarArq.printf(texto);
        arq.close();
    }

    private void jCbxFilialItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCbxFilialItemStateChanged
//        if (evt.getStateChange() == evt.SELECTED) {
//            try {
//                new Thread(new Runnable() {
//                    @Override
//                    public void run() {
//                        JDlgCarregando carregando = carregarJdialog("Atualizando listagem por filial...");
//                        carregando.setVisible(true);
//                        carregando.loadBarra("Carregando Pesquisa...", 0, 0, true);
        codfil = ((Tabfil) jCbxFilial.getSelectedItem()).getCodfil();
//                        carregarImpostos(codfil);
//                        carregando.setVisible(false);
//                        OptionPane.showMessageDialog("Mensagem", "Dados Carregados com sucesso !!!", null, () -> {
//
//                            Thread.sleep(1000);
//
//                            return null; //To change body of generated lambdas, choose Tools | Templates.
//                        });
//
//                    }
//                }).start();
//
//            } catch (Exception ex) {
//                ex.printStackTrace();
//                JDlgMensagem mensagem = new JDlgMensagem(jFramePrincipal, true, ex);
//                mensagem.setVisible(true);
//
//            }
//        }

    }//GEN-LAST:event_jCbxFilialItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            new Thread(new Runnable() {
                @Override
                public void run() {
                    JDlgCarregando carregando = carregarJdialog("");
                    carregando.setVisible(true);
                    carregando.loadBarra("Carregando Pesquisa...", 0, 0, true);
                    codfil = ((Tabfil) jCbxFilial.getSelectedItem()).getCodfil();
                    tipo = jCbxTipo.getSelectedIndex();
                    if (jTxtProd.getText() != null && !jTxtProd.getText().equals("")) {
                        tableModel.setItems(fireTabproBusiness.getProdutobyDescorCod(jTxtProd.getText(), codfil, tipo));
                        JlblTotal.setText("" + tableModel.getItens().size());
                        exportAll = false;
                    } else {
                        carregarImpostos();
                    }
                    carregando.setVisible(false);
                    OptionPane.showMessageDialog("Mensagem", "Dados Carregados com sucesso !!!", null, () -> {
                        
                        Thread.sleep(1000);
                        
                        return null; //To change body of generated lambdas, choose Tools | Templates.
                    });
                }
            }).start();
        } catch (Exception ex) {
            ex.printStackTrace();
            JDlgMensagem mensagem = new JDlgMensagem(jFramePrincipal, true, ex);
            mensagem.setVisible(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jCbxFilialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbxFilialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbxFilialActionPerformed

    private void jTxtProdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtProdKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jButton3.requestFocus();
        }
    }//GEN-LAST:event_jTxtProdKeyPressed

    private void jCbxTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCbxTipoItemStateChanged
        tipo = jCbxTipo.getSelectedIndex();
    }//GEN-LAST:event_jCbxTipoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterImposto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterImposto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterImposto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterImposto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterImposto(new JFrame()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlblTotal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<Tabfil> jCbxFilial;
    private javax.swing.JComboBox<String> jCbxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTxtProd;
    // End of variables declaration//GEN-END:variables
}
